#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

# Read in the passwords....
. /root/.digitalocean_passwords

dbaas_text=""
if [ -f "/root/.digitalocean_dbaas_credentials" ]; then
    . /root/.digitalocean_dbaas_credentials
    dbaas_text="Airflow is configured to use managed Postgres as its database. Use the following credentials to manage the database:
    Database: ${db_database}
    Host:     ${db_host}
    Port:     ${db_port}
    User:     ${db_username}
    Pass:     ${db_password}

    Redis is also configured to be used as a keystore. Use the following credentials to manage Redis:

    Host:     ${redis_host}
    Port:     ${redis_port}
    User:     ${redis_username}
    Pass:     ${redis_password}
    SSL:      Enabled"
fi

spaces_text=""
if [ -f "/root/.digitalocean_spaces_credentials" ]; then
    . /root/.digitalocean_spaces_credentials
    spaces_text="A Spaces bucket is also configured for remote loggign. Following are the bucket details:
    Bucket:         ${bucket_name}
    Host:           ${spaces_host}
    Access_Key:     ${spaces_access_key_id}
    Secret_Key:     ${spaces_secret_key}
    Region:         ${spaces_region}"
fi

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************


PASSWORD: ${PASSWORD}

Welcome to DigitalOcean's 1-Click Airflow Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Access the Airflow site
    URL: http://${myip}
    User: admin
    Pass: ${PASSWORD}

${dbaas_text}

${spaces_text}

On the server:
  * The Airflow home dir is /home/airflow/airflow
  * Example DAGs are installed at /home/airflow/airflow/dags
  * The admin Airflow password is saved in /root/.digitalocean_passwords
  * Certbot is preinstalled. Run it to configure HTTPS.

For help and more information, visit https://do.co/3bY3b67

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
