#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
if [ -f "/root/.digitalocean_dbaas_credentials" ];
then
DBAAS_PROTOCOL=$(sed -n "s/^db_protocol=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)
DBAAS_HOST=$(sed -n "s/^db_host=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)
DBAAS_PORT=$(sed -n "s/^db_port=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)
DBAAS_USERNAME=$(sed -n "s/^db_username=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)
DBAAS_DATABASE_NAME=$(sed -n "s/^db_database=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)
DBAAS_PASSWORD=$(sed -n "s/^db_password=\"\(.*\)\"$/\1/p" /root/.digitalocean_dbaas_credentials)

db_message=" * DBAAS instance of MySQL is configured. Credentials are:
 Protocol: $DBAAS_PROTOCOL
 Host: $DBAAS_HOST
 Port: $DBAAS_PORT
 Username: $DBAAS_USERNAME
 Database name: $DBAAS_DATABASE_NAME
 Password: $DBAAS_PASSWORD
"

else
LOCAL_DBAAS_PASSWORD=$(sed -n "s/^root_mysql_pass=\"\(.*\)\"$/\1/p" /root/.digitalocean_password)
db_message=" * Local instance of MySQL is configured.
 Root password is: $LOCAL_DBAAS_PASSWORD
"

fi

cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click LAMP Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The LAMP 1-Click Quickstart guide: https://do.co/3gY97ha#start
 * Your LAMP website: http://$myip

On the server:
 * The default web root is located at /var/www/html
$db_message
 * Certbot is preinstalled. Run it to configure HTTPS. See
   https://do.co/3gY97ha#enable-https for more detail.

For help and more information, visit https://do.co/3gY97ha

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
