#!/bin/sh
#
# reset a matrix user password

username="$1"
random_pass="$(openssl rand -hex 20)"

if [ -z "$username" ]; then
    printf "Please specify the username to reset (@username:example.com)\n"
    exit 1
fi

if echo "$username" | grep -Eq '^@.+:.+'; then
    printf "Setting password for $username to $random_pass\n"
    hashed_pass="$(hash_password -p $random_pass)"
    cd /
    sudo -u postgres psql -c "UPDATE users SET password_hash='$hashed_pass' WHERE name='$username';" synapse
else
    printf "Username must match format: @username:example.com\n"
    exit 1
fi
