#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click MariaDB Droplet.

To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH) and 3306 (MariaDB).

On first SSH login, complete MariaDB secure installation when prompted.
After setup, connect locally with:

  mariadb -u root -p

Your Droplet IP: $myip

Service management:
  systemctl status mariadb
  systemctl start|stop|restart mariadb

For help and more information, visit https://docs.digitalocean.com/products/marketplace/

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
