#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to your new folding@home droplet! For information on how to use the
client, check out:
https://foldingathome.org/support/faq/installation-guides/linux/
https://foldingathome.org/support/faq/installation-guides/linux/command-line-options/
https://foldingathome.org/support/faq/installation-guides/configuration-guide/

Currently, folding@home is running as an anonymous donor (Anonymous), for the
default team (0), with no passkey, and at medium power. To configure this:

sudo /etc/init.d/FAHClient stop
FAHClient --configure
# enter your desired configuration
# copy/merge this configuration over to /etc/fahclient/config.xml
sudo /etc/init.d/FAHClient start

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
