#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

# Read in the passwords....
. /root/.digitalocean_passwords

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Node.js Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Use these SFTP credentials to upload files with FileZilla/WinSCP/rsync:
    Host: ${myip}
    User: ${NODE_USER}
    Pass: ${NODE_USER_PASSWORD}

In a web browser, you can view:
 * The Node.js 1-Click Quickstart guide: https://do.co/313ycRT4#start
 * The new Node site: http://$myip

On the server:
  * The Node.js application is served from /var/www/html
  * The Node.js passwords and keys are saved in /root/.digitalocean_passwords

For help and more information, visit https://do.co/313ycRT

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f "${0}")
EOF
