#!/bin/sh
myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

QM — https://${myip}/

Full access info: /root/qm_info.txt
Manage: /opt/start-qm.sh  /opt/stop-qm.sh  /opt/restart-qm.sh  /opt/status-qm.sh  /opt/update-qm.sh
Setup:  sudo /etc/setup_wizard.sh

********************************************************************************
To remove this MOTD: rm -rf $(readlink -f "${0}")
EOF
