#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

if [ -f /root/.digitalocean_passwords ]; then
    . /root/.digitalocean_passwords
fi
if [ -f /etc/default/odoo-1click ]; then
    . /etc/default/odoo-1click
fi

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Odoo Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH) and 8069 (Odoo).

To create an Odoo database, use the following credential:
    Master Password: ${admin_odoo_password}

In a web browser, you can view:
 * Your Odoo website: http://$myip:8069

On the server:
  * The passwords are saved in /root/.digitalocean_passwords
  * The config for Odoo is saved in ${ODOO_CONFIG}
  * Odoo version: ${ODOO_VERSION}

For help and more information, visit https://marketplace.digitalocean.com/apps/erp-odoo

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
