#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

To configure NFS, please read the instructions at
https://marketplace.digitalocean.com/apps/droplet-nfs-server

No NFS share is configured. You need to export NFS shares (/etc/exports), and MUST restart the NFS server (systemctl restart nfs-kernel-server).

Security settings you should know:
DigitalOcean firewall rules for droplets are not configured. UFW is being used for access control.

VPC only Access:
- If you are using NFS server inside a VPC, make sure to enable access to port 2409 for the private interface (eth1) from the VPC subnet CIDR. eg.

ufw allow in on eth1 from 10.124.0.0/20 to any port nfs

Public network Access:
- By default, ufw is enabled, SSH access is enabled, and NFS access is NOT enabled.

Checklist:
- The volume to be exported as NFS share is available, and has ownership configured, eg. chown -R nobody:nogroup /mnt/volume_sfo3_01/
- Volume exports are configured in /etc/exports, eg. /mnt/volume_sfo3_01     *(rw,sync,no_subtree_check)
- NFS server was restarted to read the updated configuration, eg. systemctl restart nfs-kernel-server
- UFW has been configured to permit NFS access. See the security section above.
- On the client machines, you have installed nfs-common (use apt-get), and mounted the NFS share, eg. mount <nfs server ip>:/mnt/volume_sfo3_01 /mnt/nfs_volume_sfo3_01
- Troubleshooting: 
  - cat /var/log/syslog | grep -i nfs
  - If NFS mount fails on client machine, open the UFW to permit all ports from the client to make sure firewall is not the issue, eg. ufw allow in on eth1 from 10.124.0.0/20

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
