#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Dokku Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS),
2375 (Docker) and 2376 (Docker).

In a web browser, you can view:
 * The Dokku 1-Click Quickstart guide: https://do.co/3nzKhrp#start
 * Your Dokku setup page: http://$myip

For help and more information, visit https://do.co/3nzKhrp

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
