#!/bin/bash
set -euo pipefail

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

BUILD_HOSTNAME="${JITSI_BUILD_HOSTNAME:-jitsi.localhost}"

read -r -p "Enter the public DNS name for this Jitsi server (for example meet.example.com): " JITSI_HOSTNAME
case "$JITSI_HOSTNAME" in
    ""|*"/"*|*" "*|.*|*.)
        echo "ERROR: enter a valid public DNS name, for example meet.example.com" >&2
        exit 1
        ;;
    "$BUILD_HOSTNAME"|localhost|*.localhost)
        echo "ERROR: ${JITSI_HOSTNAME} is not a public DNS name and cannot get a Let's Encrypt certificate." >&2
        exit 1
        ;;
esac

move_if_exists() {
    local old="$1" new="$2"
    if [ -e "$old" ] || [ -L "$old" ]; then
        mv -f "$old" "$new"
    fi
}

ensure_acme_challenge_location() {
    local nginx_conf="$1"
    [ -f "$nginx_conf" ] || return 0
    if grep -q 'location \^~ /.well-known/acme-challenge/' "$nginx_conf"; then
        return 0
    fi

    python3 - "$nginx_conf" "$JITSI_HOSTNAME" <<'PY'
import sys

path, hostname = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    lines = f.readlines()

insert = [
    "\n",
    "    location ^~ /.well-known/acme-challenge/ {\n",
    "        default_type \"text/plain\";\n",
    "        root /usr/share/jitsi-meet;\n",
    "    }\n",
    "    location = /.well-known/acme-challenge/ {\n",
    "        return 404;\n",
    "    }\n",
]

for idx, line in enumerate(lines):
    if "server_name" in line and hostname in line:
        lines[idx + 1:idx + 1] = insert
        break
else:
    raise SystemExit(f"could not find nginx server_name for {hostname} in {path}")

with open(path, "w", encoding="utf-8") as f:
    f.writelines(lines)
PY
}

ensure_self_signed_cert() {
    local cert="/etc/jitsi/meet/${JITSI_HOSTNAME}.crt"
    local key="/etc/jitsi/meet/${JITSI_HOSTNAME}.key"

    if [ -s "$cert" ] && [ -s "$key" ]; then
        return 0
    fi

    install -d -m 0755 /etc/jitsi/meet
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout "$key" \
        -out "$cert" \
        -subj "/CN=${JITSI_HOSTNAME}"
    chmod 0644 "$cert"
    chmod 0600 "$key"
}

seed_jitsi_debconf() {
    echo "jitsi-videobridge jitsi-videobridge/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-videobridge2 jitsi-videobridge/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-meet-prosody jitsi-videobridge/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-meet-prosody jitsi-meet-prosody/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-meet-web-config jitsi-meet/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-meet jitsi-meet/jvb-hostname string ${JITSI_HOSTNAME}" | debconf-set-selections
    echo "jitsi-meet jitsi-meet/jaas-choice boolean false" | debconf-set-selections
    echo "jitsi-meet-web-config jitsi-meet/jaas-choice boolean false" | debconf-set-selections
    echo "jitsi-meet-prosody jitsi-meet/jaas-choice boolean false" | debconf-set-selections
    echo "jitsi-meet jitsi-meet/cert-choice select Generate a new self-signed certificate" | debconf-set-selections
    echo "jitsi-meet-web-config jitsi-meet/cert-choice select Generate a new self-signed certificate" | debconf-set-selections
}

reconfigure_jitsi_for_domain() {
    seed_jitsi_debconf

    # Keep Prosody migration explicit in this script. Re-running the package
    # postinst during hostname migration can call prosodyctl before the new
    # VirtualHost is loaded, producing "The given hostname does not exist in
    # the config".
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure jitsi-videobridge2
    DEBIAN_FRONTEND=noninteractive dpkg-reconfigure jitsi-meet-web-config
}

ensure_prosody_host_config() {
    local prosody_conf="/etc/prosody/prosody.cfg.lua"
    local host_conf="/etc/prosody/conf.avail/${JITSI_HOSTNAME}.cfg.lua"
    local enabled_conf="/etc/prosody/conf.d/${JITSI_HOSTNAME}.cfg.lua"
    local template="/usr/share/jitsi-meet-prosody/prosody.cfg.lua-jvb.example"
    local turn_secret

    install -d -m 0755 /etc/prosody/conf.avail /etc/prosody/conf.d /etc/prosody/certs

    if [ ! -f "$host_conf" ]; then
        if [ ! -f "$template" ]; then
            echo "ERROR: Prosody config not found and Jitsi template is missing: ${template}" >&2
            exit 1
        fi

        echo "Prosody config not generated by Jitsi reconfigure; creating it from the packaged template."
        turn_secret=$(openssl rand -hex 16)
        cp "$template" "$host_conf"
        python3 - "$host_conf" "$JITSI_HOSTNAME" "$turn_secret" <<'PY'
import sys

path, hostname, turn_secret = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path, encoding="utf-8") as f:
    text = f.read()
text = text.replace("jitmeet.example.com", hostname)
text = text.replace("focusUser", "focus")
text = text.replace("__turnSecret__", turn_secret)
with open(path, "w", encoding="utf-8") as f:
    f.write(text)
PY
    fi

    ln -sf "../conf.avail/${JITSI_HOSTNAME}.cfg.lua" "$enabled_conf"

    if [ -f "$prosody_conf" ] && ! grep -q 'Include "conf\.d/\*\.cfg\.lua"' "$prosody_conf"; then
        printf '\nInclude "conf.d/*.cfg.lua"\n' >> "$prosody_conf"
    fi

    if ! grep -q "VirtualHost \"${JITSI_HOSTNAME}\"" "$host_conf"; then
        echo "ERROR: Prosody config does not define VirtualHost \"${JITSI_HOSTNAME}\"." >&2
        echo "Check ${host_conf}." >&2
        exit 1
    fi

    if [ ! -f "/var/lib/prosody/${JITSI_HOSTNAME}.crt" ]; then
        echo | prosodyctl cert generate "$JITSI_HOSTNAME"
        ln -sf "/var/lib/prosody/${JITSI_HOSTNAME}.key" "/etc/prosody/certs/${JITSI_HOSTNAME}.key"
        ln -sf "/var/lib/prosody/${JITSI_HOSTNAME}.crt" "/etc/prosody/certs/${JITSI_HOSTNAME}.crt"
    fi

    if [ ! -f "/var/lib/prosody/auth.${JITSI_HOSTNAME}.crt" ]; then
        echo | prosodyctl cert generate "auth.${JITSI_HOSTNAME}"
        ln -sf "/var/lib/prosody/auth.${JITSI_HOSTNAME}.key" "/etc/prosody/certs/auth.${JITSI_HOSTNAME}.key"
        ln -sf "/var/lib/prosody/auth.${JITSI_HOSTNAME}.crt" "/etc/prosody/certs/auth.${JITSI_HOSTNAME}.crt"
        ln -sf "/var/lib/prosody/auth.${JITSI_HOSTNAME}.crt" "/usr/local/share/ca-certificates/auth.${JITSI_HOSTNAME}.crt"
        update-ca-certificates -f
    fi
}

ensure_https_listener() {
    local nginx_conf="/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf"

    if [ ! -f "$nginx_conf" ]; then
        echo "ERROR: nginx config not found: ${nginx_conf}" >&2
        exit 1
    fi

    ensure_self_signed_cert

    python3 - "$nginx_conf" "$JITSI_HOSTNAME" <<'PY'
import re
import sys

path, hostname = sys.argv[1], sys.argv[2]
cert = f"/etc/jitsi/meet/{hostname}.crt"
key = f"/etc/jitsi/meet/{hostname}.key"

with open(path, encoding="utf-8") as f:
    text = f.read()

def server_blocks(nginx_text):
    for match in re.finditer(r"(?m)^[ \t]*server[ \t]*\{", nginx_text):
        depth = 0
        pos = match.start()
        while pos < len(nginx_text):
            char = nginx_text[pos]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
                if depth == 0:
                    yield match.start(), pos + 1, nginx_text[match.start():pos + 1]
                    break
            pos += 1

def has_hostname(block):
    return re.search(rf"^[ \t]*server_name[ \t]+.*\b{re.escape(hostname)}\b", block, re.M)

def is_redirect_block(block):
    return re.search(r"^[ \t]*return[ \t]+30[1278][ \t]+https://", block, re.M)

def is_app_block(block):
    return (
        re.search(r"^[ \t]*root[ \t]+/usr/share/jitsi-meet;", block, re.M)
        or "set $config_js_location" in block
        or "location = /config.js" in block
    )

blocks = list(server_blocks(text))
replacements = []
target = None

for start, end, block in blocks:
    if not has_hostname(block):
        continue

    if is_redirect_block(block):
        # The HTTP redirect block must never also listen on 443, otherwise
        # https:// requests redirect to themselves forever.
        cleaned = re.sub(r"(?m)^[ \t]*listen[ \t]+(?:\[::\]:)?443\b[^\n]*;\n?", "", block)
        cleaned = re.sub(r"(?m)^[ \t]*ssl_certificate(?:_key)?[ \t]+[^\n]+;\n?", "", cleaned)
        if cleaned != block:
            replacements.append((start, end, cleaned))
        continue

    if is_app_block(block):
        target = (start, end, block)
        break

if target is None:
    raise SystemExit(f"could not find Jitsi nginx application server block for {hostname} in {path}")

start, end, block = target
insert = []
if not re.search(r"^[ \t]*listen[ \t]+443\b", block, re.M):
    insert.append("    listen 443 ssl http2;\n")
if not re.search(r"^[ \t]*listen[ \t]+\[::\]:443\b", block, re.M):
    insert.append("    listen [::]:443 ssl http2;\n")
if not re.search(r"^[ \t]*ssl_certificate[ \t]+", block, re.M):
    insert.append(f"    ssl_certificate {cert};\n")
if not re.search(r"^[ \t]*ssl_certificate_key[ \t]+", block, re.M):
    insert.append(f"    ssl_certificate_key {key};\n")

if insert:
    lines = block.splitlines(keepends=True)
    for idx, line in enumerate(lines):
        if re.search(rf"^[ \t]*server_name[ \t]+.*\b{re.escape(hostname)}\b", line):
            lines[idx + 1:idx + 1] = insert
            break
    else:
        raise SystemExit(f"could not find server_name line for {hostname} in {path}")
    block = "".join(lines)
    replacements.append((start, end, block))

for start, end, replacement in sorted(replacements, reverse=True):
    text = text[:start] + replacement + text[end:]

with open(path, "w", encoding="utf-8") as f:
    f.write(text)
PY

    if ! python3 - "$nginx_conf" "$JITSI_HOSTNAME" <<'PY'
import re
import sys

path, hostname = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    text = f.read()

def is_redirect_block(block):
    return re.search(r"^[ \t]*return[ \t]+30[1278][ \t]+https://", block, re.M)

def is_app_block(block):
    return (
        re.search(r"^[ \t]*root[ \t]+/usr/share/jitsi-meet;", block, re.M)
        or "set $config_js_location" in block
        or "location = /config.js" in block
    )

for match in re.finditer(r"(?m)^[ \t]*server[ \t]*\{", text):
    depth = 0
    pos = match.start()
    while pos < len(text):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                block = text[match.start():pos + 1]
                if (
                    re.search(rf"^[ \t]*server_name[ \t]+.*\b{re.escape(hostname)}\b", block, re.M)
                    and not is_redirect_block(block)
                    and is_app_block(block)
                    and re.search(r"^[ \t]*listen[ \t]+(?:\[::\]:)?443\b", block, re.M)
                ):
                    sys.exit(0)
                break
        pos += 1

sys.exit(1)
PY
    then
        echo "ERROR: nginx still has no active HTTPS listener for ${JITSI_HOSTNAME}." >&2
        echo "Check ${nginx_conf}." >&2
        exit 1
    fi
}

install_letsencrypt_cert() {
    local email_args=()

    if [ -n "${LETSENCRYPT_EMAIL:-}" ]; then
        email_args=(--email "$LETSENCRYPT_EMAIL")
    else
        email_args=(--register-unsafely-without-email)
    fi

    certbot certonly \
        --webroot \
        --webroot-path /usr/share/jitsi-meet \
        --domain "$JITSI_HOSTNAME" \
        --agree-tos \
        --non-interactive \
        --keep-until-expiring \
        "${email_args[@]}"

    ln -sf "/etc/letsencrypt/live/${JITSI_HOSTNAME}/fullchain.pem" "/etc/jitsi/meet/${JITSI_HOSTNAME}.crt"
    ln -sf "/etc/letsencrypt/live/${JITSI_HOSTNAME}/privkey.pem" "/etc/jitsi/meet/${JITSI_HOSTNAME}.key"

    install -d -m 0755 /etc/letsencrypt/renewal-hooks/deploy
    cat > /etc/letsencrypt/renewal-hooks/deploy/jitsi-meet-coturn <<'EOF'
#!/bin/sh
set -e

for domain in ${RENEWED_DOMAINS:-}; do
    if [ -x /usr/share/jitsi-meet/scripts/coturn-le-update.sh ]; then
        /usr/share/jitsi-meet/scripts/coturn-le-update.sh "$domain" || true
    fi
done

systemctl reload nginx.service >/dev/null 2>&1 || true
EOF
    chmod 0755 /etc/letsencrypt/renewal-hooks/deploy/jitsi-meet-coturn

    if [ -x /usr/share/jitsi-meet/scripts/coturn-le-update.sh ]; then
        /usr/share/jitsi-meet/scripts/coturn-le-update.sh "$JITSI_HOSTNAME" || true
    fi
}

printf "\n-------------------------\nUpdating the system\n-------------------------\n"

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y upgrade

printf "\n-------------------------\nConfiguring Jitsi for your domain\n-------------------------\n"

hostnamectl set-hostname "$JITSI_HOSTNAME" || true
PUBLIC_IP=$(curl -fsS --retry 3 --retry-connrefused --max-time 3 \
    http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address 2>/dev/null || hostname -I | awk '{print $1}')
if ! grep -q "[[:space:]]${JITSI_HOSTNAME}\\b" /etc/hosts 2>/dev/null; then
    printf '%s %s\n' "$PUBLIC_IP" "$JITSI_HOSTNAME" >> /etc/hosts
fi

move_if_exists "/etc/prosody/conf.avail/${BUILD_HOSTNAME}.cfg.lua" "/etc/prosody/conf.avail/${JITSI_HOSTNAME}.cfg.lua"
rm -f "/etc/prosody/conf.d/${BUILD_HOSTNAME}.cfg.lua"
if [ -f "/etc/prosody/conf.avail/${JITSI_HOSTNAME}.cfg.lua" ]; then
    ln -sf "../conf.avail/${JITSI_HOSTNAME}.cfg.lua" "/etc/prosody/conf.d/${JITSI_HOSTNAME}.cfg.lua"
fi

move_if_exists "/etc/jitsi/meet/${BUILD_HOSTNAME}-config.js" "/etc/jitsi/meet/${JITSI_HOSTNAME}-config.js"
move_if_exists "/etc/jitsi/meet/${BUILD_HOSTNAME}.crt" "/etc/jitsi/meet/${JITSI_HOSTNAME}.crt"
move_if_exists "/etc/jitsi/meet/${BUILD_HOSTNAME}.key" "/etc/jitsi/meet/${JITSI_HOSTNAME}.key"
move_if_exists "/var/lib/prosody/${BUILD_HOSTNAME}.crt" "/var/lib/prosody/${JITSI_HOSTNAME}.crt"
move_if_exists "/var/lib/prosody/${BUILD_HOSTNAME}.key" "/var/lib/prosody/${JITSI_HOSTNAME}.key"
move_if_exists "/etc/nginx/sites-available/${BUILD_HOSTNAME}.conf" "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf"
rm -f "/etc/nginx/sites-enabled/${BUILD_HOSTNAME}.conf"

reconfigure_jitsi_for_domain
move_if_exists "/etc/nginx/sites-available/${BUILD_HOSTNAME}.conf" "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf"

if [ -f "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf" ]; then
    ln -sf "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf" "/etc/nginx/sites-enabled/${JITSI_HOSTNAME}.conf"
elif [ -f /usr/share/jitsi-meet-web-config/jitsi-meet.example ]; then
    echo "nginx config not generated by Jitsi reconfigure; creating it from the packaged template."
    cp /usr/share/jitsi-meet-web-config/jitsi-meet.example "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf"
    python3 - "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf" "$JITSI_HOSTNAME" <<'PY'
import sys

path, hostname = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    text = f.read()
text = text.replace("jitsi-meet.example.com", hostname)
with open(path, "w", encoding="utf-8") as f:
    f.write(text)
PY
    ln -sf "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf" "/etc/nginx/sites-enabled/${JITSI_HOSTNAME}.conf"
else
    echo "ERROR: nginx config not found after Jitsi reconfigure: /etc/nginx/sites-available/${JITSI_HOSTNAME}.conf" >&2
    echo "Available nginx sites:" >&2
    ls -1 /etc/nginx/sites-available 2>/dev/null | sed 's/^/  - /' >&2 || true
    exit 1
fi

grep -rl "$BUILD_HOSTNAME" /etc/jitsi /etc/prosody /etc/nginx 2>/dev/null | \
    xargs -r sed -i "s/${BUILD_HOSTNAME}/${JITSI_HOSTNAME}/g"

ensure_prosody_host_config
systemctl restart prosody
ensure_https_listener

ensure_acme_challenge_location "/etc/nginx/sites-available/${JITSI_HOSTNAME}.conf"
install -d -m 0755 /usr/share/jitsi-meet/.well-known/acme-challenge
printf '%s\n' "ok" > /usr/share/jitsi-meet/.well-known/acme-challenge/do-1click-check

nginx -t
systemctl restart nginx

if ! nginx -T 2>/dev/null | grep -q "server_name .*${JITSI_HOSTNAME}"; then
    echo "ERROR: nginx did not load the Jitsi site for ${JITSI_HOSTNAME}." >&2
    echo "Check /etc/nginx/sites-enabled/${JITSI_HOSTNAME}.conf before retrying certificate setup." >&2
    exit 1
fi

if [ "$(curl -fsS -H "Host: ${JITSI_HOSTNAME}" http://127.0.0.1/.well-known/acme-challenge/do-1click-check 2>/dev/null || true)" != "ok" ]; then
    echo "ERROR: nginx is not serving Let's Encrypt challenge files for ${JITSI_HOSTNAME}." >&2
    echo "Check /etc/nginx/sites-available/${JITSI_HOSTNAME}.conf before retrying certificate setup." >&2
    exit 1
fi
rm -f /usr/share/jitsi-meet/.well-known/acme-challenge/do-1click-check

install_letsencrypt_cert
ensure_https_listener
nginx -t

# update prosody to use internal user management
for f in /etc/prosody/conf.avail/*.cfg.lua; do
    # ignore default prosody configuration files
	if [[ "$f" == */example.com.cfg.lua ]] || [[ "$f" == */jaas.cfg.lua ]] || [[ "$f" == */localhost.cfg.lua ]]; then
		continue
	fi
	printf "processing prosody conf file: ${f}\n"
	sed -i "s/authentication = \".*\"/authentication=\"internal_hashed\"/g" $f;
done

systemctl restart prosody
systemctl restart jicofo
systemctl restart jitsi-videobridge2
systemctl restart nginx

if ! curl -kfsS -H "Host: ${JITSI_HOSTNAME}" "https://127.0.0.1/" >/dev/null 2>&1; then
    echo "WARNING: nginx did not respond on local HTTPS for ${JITSI_HOSTNAME}." >&2
    echo "Check: nginx -t; systemctl status nginx; ss -tulpn | grep ':443'" >&2
fi
