#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the DigitalOcean Discourse 1-Click Application

Droplet IP: ${myip}

On your first login you will be prompted to configure your Discourse installation.
You will need a domain name pointed at this Droplet and SMTP credentials.

All Discourse scripts and files may be found in /var/discourse and the setup
utility can be run again by launching discourse-setup in that directory.

For help and more information, visit https://do.co/3dmapBw

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
