#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')

cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Jellyfin Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), 443 (HTTPS), and 8096 (Jellyfin).

- Access Jellyfin:
  * http://$myip:8096

- Jellyfin is running as a systemd service.
  To view service status run the following command:

  systemctl status jellyfin

- On first visit, complete the Jellyfin setup wizard to create an admin account
  and add your media libraries.

On the server:
  * Jellyfin configuration is stored in /etc/jellyfin
  * Jellyfin data is stored in /var/lib/jellyfin

For more information, please refer to the Getting Started Guide:
https://marketplace.digitalocean.com/apps/jellyfin

********************************************************************************
To delete this message of the day: rm -rf /etc/update-motd.d/99-one-click
EOF