#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Applications are installed under user 'ubuntu'!

To review the Readme.txt, switch to the Ubuntu user. Conda is already installed, and JupyterLab is available in the Jupyter virtual environment. To conveniently start or stop a JupyterLab instance, we have provided a notebook.sh script in the current directory. Begin by executing the following command:

su - ubuntu

============================

If you prefer to always SSH into the Ubuntu user, you can perform the following steps once. This will copy your .ssh folder from the root user to the Ubuntu user, allowing you to SSH using the same keys but with the 'ubuntu' username.

rsync --archive --chown=ubuntu:ubuntu ~/.ssh /home/ubuntu
chmod 700 /home/ubuntu/.ssh
chmod 600 /home/ubuntu/.ssh/authorized_keys

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
