#!/bin/sh

myip=$(hostname -I | awk '{print$1}')

cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click Logstash Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH).

For help and more information, visit https://marketplace.digitalocean.com/apps/logstash

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
