#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the Grafana Droplet!

In the browser, you can visit Grafana at http://$myip:3000/

For documentation visit: http://docs.grafana.org/
For help and more info visit: https://community.grafana.com/

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
