#!/bin/sh

mkdir -p /var/log/mongodb
chown -R mongodb:mongodb /var/log/mongodb

systemctl enable mongod
systemctl start mongod

#Generate root passwords.
node_user_pass=$(openssl rand -hex 24)
admin_mongodb_pass=$(openssl rand -hex 24)

# Generate some passwords
cat > /root/.digitalocean_passwords <<EOM
node_user=nodejs
node_user_password="${node_user_pass}"
admin_mongodb_password="${admin_mongodb_pass}"
EOM

source /root/.digitalocean_passwords

service mongod start

# create mongodb admin
echo 'db.createUser({user: "admin" , pwd: "'${admin_mongodb_password}'" , roles: [{ role: "userAdminAnyDatabase" , db: "admin"}], "mechanisms":["SCRAM-SHA-1"]});' | mongosh admin

service mongod stop
service mongod start --auth


# Set the nodejs user password
echo "${node_user}:${node_user_password}" | chpasswd -

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
