#!/bin/bash

chmod +x /opt/svnplus-script/*
cat >> /root/.bashrc <<EOM
/opt/svnplus-script/setup.sh
EOM

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
