#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the Gitlab 1-Click Droplet.

* You can SSH to this Droplet in a terminal as root: ssh root@$myip

* This Droplet takes several minutes to become active while Gitlab is installed
  and configured. Once the inital setup is complete, you can access this Gitlab at:
  http://$myip

* Log in the first time with the user 'root' and the password found in 
  /etc/gitlab/initial_root_password. This password is randomly generated and 
  will be stored for 24 hours.

* Gitlab is installed and configured per Gitlab's ubuntu installation guide:
  https://about.gitlab.com/install/#ubuntu

For help and more information, visit https://about.gitlab.com/

********************************************************************************

To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
