#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to your Plausible Analytics Droplet!

Documentation: https://plausible.io/docs/self-hosting
Community:     https://github.com/plausible/community-edition

First-time setup
  1. SSH in as root to finish setup (IP HTTPS or custom domain).
  2. Open https://${myip}/register and create the first account (admin).
  3. Further registrations are invite-only.

Access (after setup)
  https://${myip}

Service helpers
  /opt/status-plausible.sh
  /opt/start-plausible.sh
  /opt/stop-plausible.sh
  /opt/restart-plausible.sh
  /opt/setup-plausible-domain.sh

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
