#!/bin/sh

mkdir -p /var/log/mongodb
chown -R mongodb:mongodb /var/log/mongodb

systemctl enable mongod
systemctl start mongod

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
