#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to the DigitalOcean Valkey 1-Click Application

Valkey is a high-performance data structure server that primarily serves key/value 
workloads. It supports a wide range of native structures and an extensible plugin 
system for adding new data structures and access patterns.

Valkey is running as a systemd service and can be managed with:
 - systemctl start valkey
 - systemctl stop valkey
 - systemctl restart valkey
 - systemctl status valkey

Configuration file: /etc/valkey/valkey.conf
Log file: /var/log/valkey/valkey.log
Data directory: /var/lib/valkey

To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except:
 - 22 (SSH)
 - 6379

A strong password has been set for your Valkey instance, and can be found in the file:
/root/.digitalocean_passwords

Valkey is bound to localhost by default for security. To change this, edit the 
configuration file at /etc/valkey/valkey.conf and restart the service.

For help and more information, visit https://marketplace.digitalocean.com/apps/valkey

Additional security recommendations can be found here: https://valkey.io/docs/management/security/acl.html

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
