#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

# Read in the passwords....
. /root/.digitalocean_passwords

myip=$(hostname -I | awk '{print$1}')

cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click ElasticSearch Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), and 9200 (ElasticSearch).
ElasticSearch XPACK security is enabled.

Use these parameters to access your ElasticSearch:
    Host: ${myip}
    User: elastic
    Pass: ${ELASTIC_PASSWORD}

Use these parameters to connect Kibana to your ElasticSearch:
    Host: ${myip}
    User: kibana
    Pass: ${KIBANA_PASSWORD}

Use these parameters to connect LogStash to your ElasticSearch
    Host: ${myip}
    User: logstash_system
    Pass: ${LOGSTASH_SYSTEM_PASSWORD}

To ping your ElasticSearch, run:
    curl -k -u elastic:${ELASTIC_PASSWORD} https://${myip}:9200

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
