#!/bin/bash -x
exec > >(tee /var/log/one_click_setup.log) 2>&1

# Include the one-time commands (on droplet create) here
# JUPYTER
sudo -u ubuntu bash <<EOF
echo "Now upgrading jupyter environment"

cd ~
source /opt/conda/etc/profile.d/conda.sh

conda activate jupyter

yes| pip install  pip --upgrade
yes| pip install  -r jupyter/requirements.txt --upgrade

conda deactivate
EOF



# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
