#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click LinuxGSM Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except:
 - 22 (SSH)
 - 80 (HTTP)
 - 443 (HTTPS)
 - 27015
 - 27020
 - 27005

* You can SSH to this Droplet in a terminal as root: ssh root@$myip

[IMPORTANT]
Before creating a game server, run the command:
sudo apt-get install steamcmd
this command will install SteamCMD, during installation you can view the license.

  * To manage LinuxGSM, login as linuxgsm user:
  $ su - linuxgsm

Usage: ./linuxgsm.sh [option]
Commands:
install         | Select server to install.
servername      | Enter name of game server to install. e.g ./linuxgsm.sh csgoserver
list            | List all servers available for install.

For help and more information, visit https://marketplace.digitalocean.com/apps/linuxgsm

********************************************************************************

To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
