#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's One-Click WordPress Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The WordPress One-Click Quickstart guide: https://do.co/34TfYn8#start
 * The new WordPress site: http://$myip

On the server:
 * The default web root is located at /var/www/html
 * If you're using the embedded database, the MySQL root password
   and MySQL wordpress user password are saved in /root/.digitalocean_password
   If you've opted in to using a DBaaS instance with DigitalOcean, you will
   find your credentials written to /root/.digitalocean_dbaas_credentials and
   you will have access to a DATABASE_URL environment variable holding your
   database connection string.
 * The must-use WordPress security plugin, fail2ban, is located at
   /var/www/html/wp-content/mu-plugins/fail2ban.php
 * Certbot is preinstalled. Run it to configure HTTPS. See
   https://do.co/34TfYn8#enable-https for more detail.
 * For security, xmlrpc calls are blocked by default.  This block can be
    disabled by running "a2disconf block-xmlrpc" in the terminal.

IMPORTANT:
   After connecting to the Droplet for the first time,
   immediately add the WordPress administrator at http://$myip.

For help and more information, visit https://do.co/34TfYn8

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
