---
- name: Install | Setup nofile limit for kafka user
  community.general.pam_limits:
    domain: kafka
    limit_type: soft
    limit_item: nofile
    value: "65536"

- name: Install | Check if kafka folder is empty so we don't download kafka again
  find:
    paths: "{{ kafka_dir }}"
  register: kafka_files_found

- name: Install | Download kafka
  when: kafka_files_found.matched == 0
  get_url:
    url: "{{ kafka_url }}"
    checksum: "{{ kafka_archive_checksum }}"
    dest: "/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tar.gz"

- name: Install | Unpack tarball
  when: kafka_files_found.matched == 0
  unarchive:
    copy: no
    src: "/tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tar.gz"
    dest: "{{ kafka_dir }}"
    extra_opts:
      - --strip-components=1

- name: Install | Change kafka folder ownership to kafka
  file:
    path: "{{ kafka_dir }}"
    owner: kafka
    group: kafka
    recurse: yes

- name: Install | Restart rsyslog service
  service:
    name: rsyslog
    enabled: yes
    state: restarted
