#!/bin/sh

set -e

# Generate a per-Droplet Odoo master password.
admin_odoo_pass=$(openssl rand -hex 24)

cat > /root/.digitalocean_passwords << EOM
admin_odoo_password="${admin_odoo_pass}"
EOM

config_line="admin_passwd = $admin_odoo_pass"
printf '%s\n' "$config_line" >> /etc/odoo18.conf

systemctl daemon-reload
systemctl start odoo18

# Remove the ssh force logout command.
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
