#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

# Read in the passwords....
. /root/.digitalocean_passwords

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's 1-Click MERN Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Use these SFTP credentials to upload files with FileZilla/WinSCP/rsync:
    Host: ${myip}
    User: ${node_user}
    Pass: ${node_user_password}

Access to MongoDB:
    Username: admin
    Password: ${admin_mongodb_password}

In a web browser, you can view:
 * The MERN 1-Click Quickstart guide: link to Getting started after deploying MERN

On the server:
  * The default web root is located at /var/www/html
  * MongoDB is running on port 27017 and is bound to the local interface.
  * The passwords and keys are saved in /root/.digitalocean_passwords

For help and more information, visit link to 1-click

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
