#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

# Install latest updates on first boot
cd /srv/supabase/supabase/docker
git pull

docker compose up -d

ln -s /etc/nginx/sites-available/supabase /etc/nginx/sites-enabled/supabase
unlink /etc/nginx/sites-enabled/default

systemctl restart nginx

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
