#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of droplets
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

# Enable Firewall
ufw limit ssh
ufw allow http
ufw allow https
ufw --force enable

# Install latest updates on first boot
cd /var/discourse
git pull

DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -qqy upgrade
