#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

. /root/.digitalocean_password
myip=$(hostname -I | awk '{print$1}')
export TERM=xterm-256color
cat <<EOF
********************************************************************************

Welcome to DigitalOcean's One-Click Ghost Droplet.
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

For help and more information, visit https://marketplace.digitalocean.com/apps/ghost

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
