---
opensearch_home: /opt/opensearch
opensearch_config_home: /opt/opensearch/config
opensearch_config_file: /opt/opensearch/config/opensearch.yml
opensearch_url: https://artifacts.opensearch.org/releases/bundle/opensearch/1.3.1/opensearch-1.3.1-linux-x64.tar.gz
opensearch_checksum: "sha256:a5863c08a9a7cc25fb7171242df37c8225a21027ff7283527343681cc1875f61"

opensearch_dashboards_home: /opt/opensearch-dashboards
opensearch_dashboards_config_home: /opt/opensearch-dashboards/config
opensearch_dashboards_config_file: /opt/opensearch-dashboards/config/opensearch_dashboards.yml
opensearch_dashboards_url: https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/1.3.1/opensearch-dashboards-1.3.1-linux-x64.tar.gz
opensearch_dashboards_checksum: "sha256:4887964a48df578dfddee9d5d43350265ba48f4f408045ea1ede62d9322cbdb7"

opensearch_user: opensearch
opensearch_group: opensearch

opensearch_plugin_bin_path: /opt/opensearch/bin/opensearch-plugin
opensearch_security_plugin_conf_path: /opt/opensearch/plugins/opensearch-security/securityconfig
opensearch_security_plugin_tools_path: /opt/opensearch/plugins/opensearch-security/tools

systemctl_path: /etc/systemd/system

nodecerts_home: /opt/opensearch-nodecerts