#!/bin/bash

cat >> /root/.bashrc <<EOM
chmod +x /root/plausible-setup.sh
/root/plausible-setup.sh
EOM

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
